export const tagConverter = {
  html_css: "HTML5 / CSS3",
  javascript: "Javascript ES6",
  react_js: "React.js",
  next_js: "Next.js",
  vue_js: "Vue.js",
  svelte_js: "Svelte.js",
  ruby_on_rails: "Ruby on Rails",
  sass_scss: "Sass / SCSS",
  bootstrap: "Bootstrap",
  api_fetching: "API fetching",
  fullstack: "Fullstack",
  frontend: "Frontend",
  backend: "Backend",
  figma: "Figma",
  product_management: "Product management",
  stimulus_js: "Stimulus.js",
  css_in_js: "CSS-in-JS",
  styled_components: "Styled-components",
  coffeescript: "CoffeeScript",
  wordpress: "Wordpress",
  database_design: "Database design",
}
